### ISSUE TITLE
Type synonyms involving tuples and function types are broken

### ISSUE THREAD

**Issue by RalfJung** [AnyDSL/thorin#1] opened 2014-10-01 16:16 UTC
See the branch "impala-fail2" in imbatracer: https://github.com/AnyDSL/imbatracer/tree/impala-fail2 . The last commit shows the change leading to the breakage.

**Comment by richardmembarth** [comment] 2015-11-01 01:19
duplicate of AnyDSL/impala#12

**Closed by richardmembarth** 2015-11-01 01:19 UTC
